#define USB_SUSPEND_WAKEUP_DELAY 0
#define FIRMWARE_VERSION u8"xLxgo/xX4KK"
#define RAW_USAGE_PAGE 0xfacc
#define RAW_USAGE_ID 0x41
#define LAYER_STATE_8BIT

// #define RGB_MATRIX_STARTUP_SPD 60

#define LEADER_HASH_ENABLE
#define LEADER_HASH_PER_KEY_TIMING

#define SCAN_MOD_ENABLE

#define RAWHID_MOD_ENABLE

#define COUNTER_KEYS_ENABLE